### ISSUE TITLE
grafana-sysdig-datasource

### ISSUE THREAD

**Issue by placidchat** [draios/grafana-sysdig-datasource#33] opened 2018-09-10 09:38 UTC
The readme says to install from source, the user needs to copy to the /var/lib/grafana/plugin grafana directory. But running grafana with the sysdig data source, an error message gets generated. 

ES module A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`. Instantiating http://localhost:3000/public/plugins/sysdig/module.js 

How can i resolve this?

**Comment by davideschiera** [comment] 2018-09-11 02:04
@placidchat the problem might be related to the fact that you are copying the source code to `/var/lib/grafana/plugin`. Note that the datasource must be compiled to make it usable by Grafana. You can download the prebuilt datasource at https://download.sysdig.com/stable/grafana-sysdig-datasource/grafana-sysdig-datasource-v0.2.tgz.

Does this help?

**Comment by placidchat** [comment] 2018-09-11 04:37
I've run yarn on the dependencies and copied that across as well. Is there something else i should tweak?

**Comment by placidchat** [comment] 2018-09-11 05:00
I've rerun yarn and recopied the files, it seems to be working

**Comment by davideschiera** [comment] 2018-09-11 16:13
That's good news! Maybe there was some leftover from the initial copy. When I need to make a one-time build I run the following from the datasource directory (sitting at the same level as Grafana sourcecode):

```
npm run build && cp -r dist/* ../grafana/src/github.com/grafana/grafana/data/plugins/sysdig
```

Hope this helps! Let me know if there are still some issues around the build. Thanks!

**Comment by davideschiera** [comment] 2018-09-17 16:53
@placidchat hoping that the issue is no longer happening, I'm going to close this issue. Please feel free to reopen it if it's still a problem for you. Thanks!

**Closed by davideschiera** 2018-09-17 16:53 UTC
